### ISSUE TITLE
Option for lighter comment color?

### ISSUE THREAD

**Issue by FX-Wood** [Everblush/everblush.vim#29]
Hey! Love the theme, and am pretty new to vim/nvim. Is there a clever way to lighten up the comment/line number color? For whatever reason I'm having trouble seeing comments/line numbers on my setup. 

Here's my current config:
```
require'everblush'.setup{ nvim_tree = { contrast = true } }
```
here's a screenshot of what it looks like for me (it reads a little bit darker on my monitor):
![image](https://user-images.githubusercontent.com/40310772/191386479-0439f4ac-93d4-44f1-952f-189d79bae776.png)

and a link to my (nascent) dotfiles: https://github.com/FX-Wood/dev-env/tree/main/nvim

Happy to submit a PR if you can point me in the right direction

**Comment by FX-Wood** [comment]
whoops, wrong plugin, sorry. Was looking for the nvim plugin located here: https://github.com/Everblush/everblush.nvim

Here's the answer to the question there:
https://github.com/Everblush/everblush.nvim#overriding-colors

**Comment by Mangeshrex** [comment]
everything gone well right ?

**Comment by FX-Wood** [comment]
yes, all good-- thank you for following up
