### ISSUE TITLE
Update to the latest version, error messages are shown

### ISSUE THREAD

**Issue by tan-wei** [Everblush/everblush.vim#34]
Env:
   - git commit: [9ffb902](https://github.com/Everblush/everblush.vim/commit/9ffb902540ddb1c0743e5e40633c80efd75a6823)
   - neovim version: 0.8.2
 
Startup will report error messages:
![图片](https://user-images.githubusercontent.com/28227509/215016130-92ed590f-45c6-4165-a356-d28b9c98a835.png)

Which is here:
https://github.com/Everblush/everblush.vim/blob/9ffb902540ddb1c0743e5e40633c80efd75a6823/colors/everblush.vim#L16

**Comment by prateektade** [comment]
Hi @tan-wei! If you are using Neovim 0.8+ I will recommend using our [Neovim](https://github.com/Everblush/nvim) colorscheme written completely in Lua. This colorscheme is specifically designed for Vim using [vim-colortemplate](https://github.com/lifepillar/vim-colortemplate), and this variable declaration is automatically generated by that tool.

**Comment by tan-wei** [comment]
OK. Thanks, I'll migrate to the Neovim compatible version.
